export const GET_POKEMON_LIST = "GET_POKEMON_LIST";
export const GET_POKEMON_DETAIL = "GET_POKEMON_DETAIL";
export const SAVE_POKEMON = "SAVE_POKEMON";
export const RELEASE_POKEMON = "RELEASE_POKEMON";
export const CLEAR_POKEMON_DETAIL = "CLEAR_POKEMON_DETAIL";